# Writing figures and the generated tex. Nothing here decides anything; it only
# formats what the panels and the statistics already computed.

save_fig <- function(plot, name, width, height) {
  # Fail early if a panel forgot to source the shared, embedded-font theme.
  figure_font_family()
  # Every figure is included at exactly its canvas width, so a canvas that is
  # neither the text width nor the single-column width would be rescaled by
  # TeX and its type would no longer match the shared theme.  Which of the two
  # a figure uses is declared in FIGURE_LAYOUT.tsv and mirrored by the
  # \includegraphics width; only the height is a free per-figure decision.
  allowed <- c(FIGURE_CANVAS_WIDTH_IN, FIGURE_COLUMN_WIDTH_IN)
  if (!any(vapply(allowed, function(w) isTRUE(all.equal(width, w)), logical(1)))) {
    stop(sprintf("%s: canvas width %.3f in must be the text width %.3f in or the column width %.3f in",
                 name, width, FIGURE_CANVAS_WIDTH_IN, FIGURE_COLUMN_WIDTH_IN))
  }
  ggplot2::ggsave(file.path("figs", "out", paste0(name, ".pdf")), plot,
                  width = width, height = height, units = "in", device = cairo_pdf)
  invisible(NULL)
}

# Use the same family in every layer, including symbols supplied as ordinary
# Unicode text.  Keeping this check next to the device call makes it harder for
# a future panel to silently fall back to a host-dependent default.
figure_font_family <- function() {
  if (!exists("FIGURE_FONT_FAMILY", inherits = TRUE)) {
    stop("FIGURE_FONT_FAMILY must be declared by figs/rtx_theme.R")
  }
  FIGURE_FONT_FAMILY
}

fmt <- function(x, digits = 2) {
  # Avoid printing a rounded negative zero (for example, -0.0047 at two
  # decimals).  The underlying receipt remains unchanged; only the displayed
  # representation is normalised at the requested precision.
  threshold <- 0.5 * 10^(-digits)
  value <- ifelse(abs(x) < threshold, 0, x)
  formatC(value, format = "f", digits = digits)
}

# Scientific notation is reserved for probabilities below 10^-3, where a long
# run of zeros is harder to scan and can be mistaken for truncation.  The
# mantissa retains three significant digits and the ASCII `e` form is deliberate:
# it is portable in plain TeX tables and does not trigger a second symbol font.
sci <- function(x, digits = 3) {
  value <- formatC(x, format = "e", digits = digits - 1)
  sub("e\\+?(-?)0+", "e\\1", value)
}

# An exact signed-rank p on ten pairs takes a small number of distinct values.
# Rounding them all to three places would print two different tests as the same
# number, so the small ones keep their significant digits instead.
p_cell <- function(p) {
  if (is.na(p)) return("---")
  if (p < 1e-3) return(sci(p, 3))
  if (p >= 0.01) formatC(p, format = "f", digits = 3) else format(signif(p, 3), scientific = FALSE)
}

# The same rule as above for the p-values quoted in prose, where two significant
# digits are enough and a fixed width would again collapse distinct values.
pval <- function(p) {
  if (is.na(p)) return("---")
  if (p < 1e-3) sci(p, 3) else format(signif(p, 3), scientific = FALSE)
}

# A signed cell, except that values below the displayed resolution are printed
# as an unsigned zero. Without this a value that rounds to zero can appear as
# "-0.000", which is visually negative despite carrying no resolved sign.
signed_cell <- function(x, digits = 3) {
  threshold <- 0.5 * 10^(-digits)
  value <- ifelse(abs(x) < threshold, 0, x)
  ifelse(value == 0, formatC(0, format = "f", digits = digits),
         sprintf(paste0("%+.", digits, "f"), value))
}

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)

GENERATED_HEADER <- "% Generated by the figure script from hash-bound evidence. Do not hand-edit."

write_generated <- function(lines, name) {
  writeLines(c(GENERATED_HEADER, lines), file.path("tex", name))
  invisible(NULL)
}
